energiepanel/energiepanel/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path, include
from django.contrib.auth import views as auth_views
from epanel import views as epanel_views

admin.site.site_header = 'Energiepanel Admin'

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^accounts/', include('django.contrib.auth.urls')),
    re_path(r'^', include('epanel.urls')),
]

energiepanel/epanel/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
    re_path(r'^$', views.home, name='home'),
    re_path(r'^index.html/', views.home, name='home'),
    re_path(r'^signup/$', views.signup, name='signup'),
    re_path(r'^download_pdf/$', views.download_pdf, name='download_pdf'),
    re_path(r'^logout/$', views.logout, name='logout'),
    re_path(r'^overview/$', views.overview, name='overview'),
    re_path(r'^buildingdata/$', views.buildingdata, name='buildingdata'),
    re_path(r'^add_year/$', views.add_year, name='add_year'),#calculation
    re_path(r'^calculation/$', views.calculation, name='calculation'),
    re_path(r'^calculation_admin/$', views.calculation_admin, name='calculation_admin'),
    re_path(r'^pdf_admin/$', views.pdf_admin, name='pdf_admin'),
    re_path(r'^impressum/$', views.impressum, name='impressum'),
    re_path(r'^datenschutz/$', views.datenschutz, name='datenschutz'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,40})/$',
        views.activate, name='activate'),
]

energiepanel/epanel/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.validators import RegexValidator
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils.html import format_html

from datetime import datetime

class UserManager(BaseUserManager):
    """A new UserManager that uses the email as the username field"""

    use_in_migrations = True

    def _create_user(self, username, password, **extra_fields):
        if not username:
            raise ValueError('Keine Email Adresse angegeben.')
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, password=None, **extra_fields):
        """Einen Benutzer mit dem gegebenen passwort erstellen."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, password, **extra_fields)

    def create_superuser(self, username, password, **extra_fields):
        """Adminaccount erstellen."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(username, password, **extra_fields)


class User(AbstractUser):
    email = models.EmailField(_('email address'), unique=False)

    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Die Telefonnummer muss in folgendem Format eingegeben werden: '+XX123456789' (bis zu 15 Zeichen)")
    phone_number = models.CharField(validators=[phone_regex], max_length=17)

    owner = models.CharField(max_length=256)
    street = models.CharField(max_length=512)
    number = models.CharField(max_length=16)
    parz = models.CharField(max_length=64)
    city = models.CharField(max_length=64)
    plz = models.CharField(max_length=5)

    REQUIRED_FIELDS = []

    objects = UserManager()

class BuildingData(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    #gebäudedaten

    GEBAEUDEART_CHOICES = (
        ("EINFAMILIENHAUS", _("Einfamilienhaus")),
        ("2FAMILIENHAUS", _("Zweifamilienhaus")),
        ("WOHNGEBAEUDE_3_WOHNEINHEITEN", _("Wohngebäude bis 3 Wohneinheiten")),
        ("FREIE_EINGABE", _("Freie Eingabe (bitte Eintragen)")),
    )

    gebaeudeart = models.CharField(max_length=256, choices=GEBAEUDEART_CHOICES)
    gebaeudeart_freie_eingabe = models.CharField(max_length=256, null=True, blank=True)

    BAUART_CHOICES = (
        ("FREISTEHEND", _("freistehendes Haus")),
        ("ECKHAUS", _("Eckhaus")),
        ("REIHENHAUS", _("Reihenhaus"))
    )

    bauart = models.CharField(max_length=256, choices=BAUART_CHOICES)

    energiebezugsflaeche = models.PositiveIntegerField(default=200, validators=[MinValueValidator(50), MaxValueValidator(600)])
    baujahr = models.PositiveIntegerField(default=1950, validators=[MinValueValidator(1900), MaxValueValidator(2030)])

    #sanierung gebäudehülle
    sanierung_dach = models.IntegerField(validators=[MinValueValidator(1980), MaxValueValidator(2030)], null=True, blank=True)
    sanierung_aussenwaende = models.IntegerField(validators=[MinValueValidator(1980), MaxValueValidator(2030)], null=True, blank=True)
    sanierung_fenster = models.IntegerField(validators=[MinValueValidator(1980), MaxValueValidator(2030)], null=True, blank=True)
    sanierung_kellerdecken = models.IntegerField(validators=[MinValueValidator(1980), MaxValueValidator(2030)], null=True, blank=True)
    sanierung_anderes = models.IntegerField(validators=[MinValueValidator(1980), MaxValueValidator(2030)], null=True, blank=True)

    sanierung_anderes_erklaerung = models.CharField(max_length=1000, null=True, blank=True)

    #wärmeerzeugung und abgabe
    baujahr_gebaeudeheizung = models.IntegerField(default=-1, validators=[MinValueValidator(1980), MaxValueValidator(2030)])
    baujahr_warmwasseraufbereitung = models.IntegerField(default=-1, validators=[MinValueValidator(1980), MaxValueValidator(2030)])

    HEIZUNG_CHOICES = (
        ("HEIZOEL", _("Heizöl")),
        ("GAS", _("Gas")),
        ("HOLZ", _("Holz")),
        ("STROM", _("Strom")),
        ("FLUESSIGGAS", _("Flüssiggas")),
        ("SONNE", _("Sonne")),
        ("SONSTIGES", _("Sonstiges (bitte angeben)")),
    )

    HEIZUNG_OTHER_CHOICES = (
        ("NONE", _("keine")),
        ("HEIZOEL", _("Heizöl")),
        ("GAS", _("Gas")),
        ("HOLZ", _("Holz")),
        ("STROM", _("Strom")),
        ("FLUESSIGGAS", _("Flüssiggas")),
        ("SONNE", _("Sonne")),
        ("SONSTIGES", _("Sonstiges (bitte angeben)")),
    )

    heizwaerme_erzeugung_1 = models.CharField(max_length=32,default="HEIZOEL", choices = HEIZUNG_CHOICES)
    heizwaerme_erzeugung_1_sonstiges = models.CharField(max_length=128,null=True, blank=True)
    heizwaerme_erzeugung_2 = models.CharField(max_length=32,default="NONE", null=True, blank=True, choices = HEIZUNG_OTHER_CHOICES)
    heizwaerme_erzeugung_2_sonstiges = models.CharField(max_length=128,null=True, blank=True)
    heizwaerme_erzeugung_3 = models.CharField(max_length=32,default="NONE", null=True, blank=True, choices = HEIZUNG_OTHER_CHOICES)
    heizwaerme_erzeugung_3_sonstiges = models.CharField(max_length=128,null=True, blank=True)

    warmwasseraufbereitung_1 = models.CharField(max_length=32,default="HEIZOEL", choices = HEIZUNG_CHOICES)
    warmwasseraufbereitung_1_sonstiges = models.CharField(max_length=128,null=True, blank=True)
    warmwasseraufbereitung_2 = models.CharField(max_length=32,default="NONE", null=True, blank=True, choices = HEIZUNG_OTHER_CHOICES)
    warmwasseraufbereitung_2_sonstiges = models.CharField(max_length=128,null=True, blank=True)
    warmwasseraufbereitung_3 = models.CharField(max_length=32,default="NONE", null=True, blank=True, choices = HEIZUNG_OTHER_CHOICES)
    warmwasseraufbereitung_3_sonstiges = models.CharField(max_length=128,null=True, blank=True)

    leistung_waermeerzeuger = models.PositiveIntegerField(default=20, validators=[MinValueValidator(0), MaxValueValidator(50)])

    WAERMEABGABE_CHOICES = (
        ("HEIZKOERPER", _("Heizkörper")),
        ("FUSSBODENHEIZUNG", _("Fußbodenheizung")),
        ("FUSSBODENHEIZUNG_HEIZKOERPER", _("Heizkörper & Fußbodenheizung")),
        ("SONST_FLAECHENHEIZUNG", _("sonstige Flächenheizung")),
        ("SONSTIGES", _("Sonstiges (bitte angeben)")),
    )

    waermeabgabe = models.CharField(max_length=32,default="HEIZKOERPER", choices = WAERMEABGABE_CHOICES)
    waermeabgabe_sonstiges = models.CharField(max_length=128, null=True, blank=True)

    REGELUNG_WAERMEABGABE_CHOICES = (#Thermostatventile, manuelle Ventile, Stellantriebe, Stellantriebe mit Raumtemperaturregelung, sonstiges
        ("THERMOSTATVENTILE", _("Thermostatventile")),
        ("MANUELLE_VENTILE", _("manuelle Ventile")),
        ("THERMOSTAT_MANUELLE_VENTILE", _("Thermostatventile & manuelle Ventile")),
        ("STELLANTRIEBE", _("Stellantriebe")),
        ("STELLANTRIEBE_RAUMTEMP_REGELUNG", _("Stellantriebe mit Raumtemperaturregelung")),
        ("SONSTIGES", _("Sonstiges (bitte angeben)")),
    )

    regelung_waermeabgabe = models.CharField(max_length=32,default="THERMOSTATVENTILE", choices = REGELUNG_WAERMEABGABE_CHOICES)
    regelung_waermeabgabe_sonstiges = models.CharField(max_length=128, null=True, blank=True)

    #brauchwarmwasser

    BRAUCHWARMWASSER_CHOICES = (
        ("JA", _("Ja (vorhanden)")),
        ("NEIN", _("Nein (nicht vorhanden)")),
        ("NICHT_BEKANNT", _("nicht bekannt")),
    )

    brauchwarmwasserzirkulation = models.CharField(choices = BRAUCHWARMWASSER_CHOICES, max_length=32,default="NICHT_BEKANNT")
    brauchwarmwasser_speicher_inhalt = models.PositiveIntegerField(validators=[MinValueValidator(20), MaxValueValidator(500)], null=True, blank=True)

    #eigenstromproduktion

    ART_EIGENSTROM_CHOICES = (
        ("KEINE", _("keine")),
        ("PV", _("Photovoltaik")),
        ("SONSTIGES", _("Sonstiges (bitte angeben)")),
    )

    art_eigenstromanlage = models.CharField(choices = ART_EIGENSTROM_CHOICES, max_length=64,default="NONE")
    art_eigenstromanlage_sonstiges = models.CharField(max_length=128,null=True, blank=True)
    peak_leistung_eigenstromanlage = models.FloatField(validators=[MinValueValidator(0.5), MaxValueValidator(50.0)], null=True, blank=True)

    kapazitaet_batteriespeicher = models.FloatField(validators=[MinValueValidator(0.0), MaxValueValidator(10000.0)], null=True, blank=True)

    #geplante investitionen
    investition_waermeerzeugung = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100000)], null=True, blank=True)
    investition_warmwasseraufbereitung = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100000)], null=True, blank=True)
    investition_eigenstromproduktion_batteriespeicher = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(200000)], null=True, blank=True)
    investition_sanierung_gebaeudehuelle = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(500000)], null=True, blank=True)
    investition_andere = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(500000)], null=True, blank=True)

    class Meta:
        verbose_name = 'Gebäudedaten ohne Energie'
        verbose_name_plural = 'Gebäudedaten ohne Energie'


class EnergyByYear(models.Model):
    #User ist ein foreign Key, bedeutet dass ein Nutzer mehrere dieser Objekte haben kann
    user = models.ForeignKey(User, on_delete=models.CASCADE)

energiepanel/epanel/templates/acc_active_email.html
{% autoescape off %}
Guten Tag,
Um Ihre Anmeldung in dem Panel abzuschließen müssen Sie Ihre Anmeldung mit einem Klick auf diesen Link bestätigen:
https://tsb-energie-daten.de{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

energiepanel/epanel/templates/add_year.html
<!DOCTYPE html>
<html>
  <head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-icons.css' %}">
    <script src="{% static 'jquery-3.2.1.slim.min.js' %}"></script>
    <script src="{% static 'popper.min.js' %}"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <title>{% block title %}Angaben Energie pro Jahr{% endblock %}</title>
    <link href="{% static 'epanel/style.css' %}" rel="stylesheet">

    <script>
        
        var done = false;

        window.addEventListener('beforeunload', function (e) {
          if (!done){
            e.preventDefault();
            e.returnValue = '';
          }
        });
        
        $(document).ready(function() {
          $("#buildingdata_form").on("submit", function(e) {
            done = true;
            return true;
          });

          //Logic to show or hide form fields depending on html attributes
          var all = document.getElementsByTagName("*");

          let doPopovers = [];

          for (var i=0, max=all.length; i < max; i++) {
              let elem = all[i];
              if (elem.getAttribute("show-id") && elem.getAttribute("show-on")){
                console.log("found " + elem + " " + elem.getAttribute("show-id"));
                $("#"+elem.getAttribute("show-id")).css("display", "none");
                $(elem).on('input', function(e) {
                  if ($(this).attr("show-on") == $(this).prop('selectedIndex')){
                    $("#"+$(this).attr("show-id")).css("display", "inline");
                    $("#"+$(this).attr("show-id")).css("background-color", "#ffd0c9");
                  }
                  else{
                    $("#"+elem.getAttribute("show-id")).css("display", "none");
                  }
                });
              }
              //Wenn JavaScript verfügbar ist, schiebe alle Hints in Popovers
              if (elem.id.startsWith("hint_id_")){
                var header_id = elem.id.replace(/hint_id_/i, "id_");
                doPopovers.push(header_id)
                //elem2.innerHTML += 
              }

          }

          doPopovers.forEach(function(id){
            let text = document.getElementById("hint_" + id).innerHTML;
            document.getElementById("hint_" + id).remove();
            var elem2 = $("label[for='"+id+"']")[0].innerHTML += '<button type="button" class="btn btn-link btn-sm" data-toggle="popover" data-content=\''+text+'\'><i class="bi bi-info-circle"></i></button>';
            console.log($("label[for='"+id+"']")[0]);
          });

          //Enable Popovers
          $("[data-toggle=popover]").popover();

          $('body').on('click', function (e) {
            $('[data-toggle="popover"]').each(function () {
                //the 'is' for buttons that trigger popups
                //the 'has' for icons within a button that triggers a popup
                if (!$(this).is(e.target) && $(this).has(e.target).length === 0 && $('.popover').has(e.target).length === 0) {
                    $(this).popover('hide');
                }
            });
          });

          const queryString = window.location.search;
          const urlParams = new URLSearchParams(queryString);
          if (urlParams.has("j")){
            document.getElementById("id_acceptoverwrite_1").checked = true;
          }

        });
		</script>

  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark navbar-expand-lg navbar_green">
      <div class="container-fluid">
        <a class="navbar-brand" href="#"><i class="bi bi-lightning-charge fg-green"></i></a>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="/overview">Übersicht</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <br>
    <div class="container">
      <div class="row">
        <div class="col-sm-8">
          <h2>Grundangaben Endenergie pro Jahr</h2><br>
          <div class="card">
            <div class="card-header" id="gebaeudedaten">Jahr eintragen</div>
              <div class="card-body">
              {% if error_overwrite %}
                <div class="alert alert-danger" role="alert">
                  Achtung! Sie haben bereits einen Eintrag mit diesem Jahr angelegt. Bitte setzen Sie den Haken, um den bereits existierenden Datensatz zu überschreiben.
                </div>
              {% endif %}
            {% load crispy_forms_tags %}
            {% block content %}
              <form method="post" id="buildingdata_form">
                {% csrf_token %}
                  {% for field in form %}
                    {% if field.field.pv is True and eigenstrom is False %}
                      
                    {% else %}
                      {% if field.field.open_collapse %}
                        <div id="{{ field.field.collapse_id|add:"_acc"}}">
                          <div class="card">
                            <div class="card-header" id="{{ field.field.collapse_id }}">
                              <h5 class="mb-0">
                                <button class="btn btn-link collapsed" data-toggle="collapse" aria-expanded="false" data-target="#{{ field.field.collapse_id|add:"_collapse"}}" type="button">
                                  <i class="bi bi-plus-square"></i> {{ field.field.collapse_title }}
                                </button>
                              </h5>
                            </div>
                            <div id="{{ field.field.collapse_id|add:"_collapse"}}" class="collapse" data-parent="#{{ field.field.collapse_id|add:"_acc"}}">
                              <div class="card-body">
                      {% endif %}
                      <p>
                        {{ field|as_crispy_field }}
                      </p>
                      {% if field.field.after %}
                        </div>
                      </div>
                      <br><br>
                      <div class="card">
                        <div class="card-header" id="{{ field.field.after_id }}">{{ field.field.after }}</div>
                        <div class="card-body">
                      {% endif %}
                      {% if field.field.close_collapse %}
                              </div>
                            </div>
                          </div>
                        </div>
                      {% endif %}
                    {% endif %}
                  {% endfor %}
                  <button type="submit" class="btn btn-success">Abschicken</button>
                </form>
            {% endblock %}
              </div>
            </div>
        </div>
        <div class="col-sm">
          <div class="card text-white bg-info" style=" position: sticky; top: 10px;">
            <div class="card-header">
              <i class="bi bi-info-circle"></i> Info
            </div>
            <div class="card-body">
              Um fortzufahren müssen sie die Energiedaten der letzten 3 Jahre angeben.<br><br> Werte für zukünftige Jahre können eingetragen werden, um die

Entwicklung in die Zukunft zu sehen.

Aus dem Verlauf in der Vergangenheit kann mit eigenen Zahlen in der Zukunft abgeschätzt werden. Sie können so sehen, ob Ihre Erwartungen erfüllt werden. Auch kann die Prognose genutzt werden, um mit dem Energieberater zukünftige Werte zu besprechen.
            </div>
          </div>
          </div>
        </div>
      </div>
      <br>
    </div>
    <br><br>
    <!-- Footer -->
    <div style="position: fixed; bottom: 0; right: 0; text-align: right; background-color: rgba(117,255,0,0.6); padding: 6px; border-top-left-radius: 8px;">  
      <!-- Copyright -->
      <div>
        &nbsp;<a class="text-dark" href="/impressum/">Impressum</a>&nbsp;|&nbsp;<a class="text-dark" href="/datenschutz/">Datenschutzerklärung</a>&nbsp;
      </div>
      <!-- Copyright -->
    </div>
  </body>
</html>

energiepanel/epanel/templates/buildingdata.html
<!DOCTYPE html>
<html>
  <head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-icons.css' %}">
    <script src="{% static 'jquery-3.2.1.slim.min.js' %}"></script>
    <script src="{% static 'popper.min.js' %}"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <title>{% block title %}Gebäudedaten{% endblock %}</title>
    <link href="{% static 'epanel/style.css' %}" rel="stylesheet">

    <script>
        
        var done = false;
        var warmwasser_erzeugung_changed = false;

        window.addEventListener('beforeunload', function (e) {
          if (!done){
            e.preventDefault();
            e.returnValue = '';
          }
        });
        
        $(document).ready(function() {

          $("#buildingdata_form").on("submit", function(e) {
            done = true;
            return true;
          });

          //Logic to show or hide form fields depending on html attributes
          var all = document.getElementsByTagName("*");

          let doPopovers = []

          for (var i=0, max=all.length; i < max; i++) {
              let elem = all[i];
              if (elem.getAttribute("show-id") && elem.getAttribute("show-on")){
                $("#"+elem.getAttribute("show-id")).css("display", "none");
                $(elem).on('input', function(e) {
                  if ($(this).attr("show-on") == $(this).prop('selectedIndex')){
                    $("#"+$(this).attr("show-id")).css("display", "inline");
                    $("#"+$(this).attr("show-id")).css("background-color", "#ffd0c9");
                  }
                  else{
                    $("#"+elem.getAttribute("show-id")).css("display", "none");
                  }
                });
              }

              //Wenn JavaScript verfügbar ist, schiebe alle Hints in Popovers
              if (elem.id.startsWith("hint_id_")){
                var header_id = elem.id.replace(/hint_id_/i, "id_");
                doPopovers.push(header_id)
                //elem2.innerHTML += 
              }

          }

          doPopovers.forEach(function(id){
            let text = document.getElementById("hint_" + id).innerHTML;
            document.getElementById("hint_" + id).remove();
            var elem2 = $("label[for='"+id+"']")[0].innerHTML += '<button type="button" class="btn btn-link btn-sm" data-toggle="popover" data-content=\''+text+'\'><i class="bi bi-info-circle"></i></button>';
          });

          //Enable Popovers
          $("[data-toggle=popover]").popover();

          $('body').on('click', function (e) {
            $('[data-toggle="popover"]').each(function () {
                //the 'is' for buttons that trigger popups
                //the 'has' for icons within a button that triggers a popup
                if (!$(this).is(e.target) && $(this).has(e.target).length === 0 && $('.popover').has(e.target).length === 0) {
                    $(this).popover('hide');
                }
            });
          });

          //Events
          $("#id_heizwaerme_erzeugung_1").on('change', function() {
            if (!warmwasser_erzeugung_changed && this.value != "SONSTIGES"){
              $("#id_warmwasseraufbereitung_1").val(this.value);
            }
          });

          $("#id_warmwasseraufbereitung_1").on('change', function() {
            warmwasser_erzeugung_changed = true;
          });

        });
		</script>

  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark navbar-expand-lg navbar_green">
      <div class="container-fluid">
        <a class="navbar-brand" href="#"><i class="bi bi-lightning-charge fg-green"></i></a>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="/overview">Übersicht</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <br>
    <div class="container">
      <div class="row">
        <div class="col-sm-8">
          <h2>Gebäude Grundangaben</h2><br>
          <div class="card">
            <div class="card-header" id="gebaeudedaten">Gebäudedaten</div>
              <div class="card-body">
            {% load crispy_forms_tags %}
            {% block content %}
              <form method="post" id="buildingdata_form">
                {% csrf_token %}
                  {% for field in form %}
                    {% if field.field.open_collapse %}
                      <div id="{{ field.field.collapse_id|add:"_acc"}}">
                        <div class="card">
                          <div class="card-header" id="{{ field.field.collapse_id }}">
                            <h5 class="mb-0">
                              <button class="btn btn-link collapsed" data-toggle="collapse" aria-expanded="false" data-target="#{{ field.field.collapse_id|add:"_collapse"}}" type="button">
                                <i class="bi bi-plus-square"></i> {{ field.field.collapse_title }}
                              </button>
                            </h5>
                          </div>
                          <div id="{{ field.field.collapse_id|add:"_collapse"}}" class="collapse" data-parent="#{{ field.field.collapse_id|add:"_acc"}}">
                            <div class="card-body">
                    {% endif %}
                    <p>
                      {{ field|as_crispy_field }}
                    </p>
                    {% if field.field.after %}
                      </div>
                    </div>
                    <br><br>
                    <div class="card">
                      <div class="card-header" id="{{ field.field.after_id }}">{{ field.field.after }}</div>
                      <div class="card-body">
                    {% endif %}
                    {% if field.field.close_collapse %}
                            </div>
                          </div>
                        </div>
                      </div>
                    {% endif %}
                  {% endfor %}
                  <button type="submit" class="btn btn-success">Abschicken</button>
                </form>
            {% endblock %}
              </div>
            </div>
        </div>
        <div class="col-sm">
          <div class="card text-white bg-info" style=" position: sticky; top: 10px;">
            <div class="card-header">
              <i class="bi bi-info-circle"></i> Übersicht
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item text-white bg-info"><a class="deco-none-white" href="#gebaeudedaten">Gebäudedaten</a></li>
              <li class="list-group-item text-white bg-info"><a class="deco-none-white" href="#sanierung">Sanierung Gebäudehülle</a></li>
              <li class="list-group-item text-white bg-info"><a class="deco-none-white" href="#waerrmeerzeugung">Wärmeerzeugung und Abgabe</a></li>
              <li class="list-group-item text-white bg-info"><a class="deco-none-white" href="#brauchwarmwasser">Brauchwarmwasser</a></li>
              <li class="list-group-item text-white bg-info"><a class="deco-none-white" href="#eigenstromproduktion">Eigenstromproduktion & Stromspeicher</a></li>
              <li class="list-group-item text-white bg-info"><a class="deco-none-white" href="#investitionen">Geplante Investitionen</a></li>
            </ul>
          </div>
        </div>
      </div>
      <br>
    </div>
    <br><br>
    <!-- Footer -->
    <div style="position: fixed; bottom: 0; right: 0; text-align: right; background-color: rgba(117,255,0,0.6); padding: 6px; border-top-left-radius: 8px;">  
      <!-- Copyright -->
      <div>
        &nbsp;<a class="text-dark" href="/impressum/">Impressum</a>&nbsp;|&nbsp;<a class="text-dark" href="/datenschutz/">Datenschutzerklärung</a>&nbsp;
      </div>
      <!-- Copyright -->
    </div>
  </body>
</html>